Add mustgather registry image to relatedImage
openshift/oadp-operator pull request #1135
Opened 2023-08-21 18:59 UTC by kaovilai

2023-08-21 19:02 UTC, kaovilai commented
/cc @weshayutin @rayfordj

2023-08-21 20:20 UTC, rayfordj requested changes
See review/comments on https://github.com/openshift/oadp-operator/pull/1136

2023-08-21 21:31 UTC, rayfordj requested changes

2023-08-21 21:31 UTC, rayfordj commented on bundle/manifests/oadp-operator.clusterserviceversion.yaml
> +                  value: registry.redhat.io/oadp/oadp-mustgather-rhel8
```suggestion
                  value: registry.redhat.io/oadp/oadp-mustgather-rhel8:v1.2
```

2023-08-21 21:31 UTC, rayfordj commented on bundle/manifests/oadp-operator.clusterserviceversion.yaml
> +  - image: registry.redhat.io/oadp/oadp-mustgather-rhel8
```suggestion
  - image: registry.redhat.io/oadp/oadp-mustgather-rhel8:v1.2
```

2023-08-21 21:31 UTC, rayfordj commented on config/manager/manager.yaml
> +            value: registry.redhat.io/oadp/oadp-mustgather-rhel8
```suggestion
            value: registry.redhat.io/oadp/oadp-mustgather-rhel8:v1.2
```

2023-08-22 18:12 UTC, rayfordj approved these changes
/lgtm

2023-08-22 18:12 UTC, rayfordj commented
/retest

2023-08-22 21:18 UTC, sseago approved these changes

2023-08-22 22:46 UTC, merged

2023-08-23 12:12 UTC, weshayutin commented
/cherry-pick oadp-1.2