Update velero dep after rebase 2023-10-24
openshift/oadp-operator pull request #1197
Opened 2023-10-24 17:53 UTC by sseago

2023-10-24 17:55 UTC, weshayutin submitted a review, later dismissed

2023-10-24 18:10 UTC, kaovilai approved these changes

2023-10-24 20:08 UTC, mateusoliveira43 requested changes
Changing the error to warning did not fix E2E tests, because we do a regex filter by the word error (here https://github.com/openshift/oadp-operator/blob/master/tests/e2e/lib/velero_helpers.go#L194) and the warning message has error on it.

if we can change the regex to something like
```go
errorRegex, err := regexp.Compile("level=error") // only check for error logs
```
would be more appropriate

2023-10-24 23:39 UTC, kaovilai approved these changes
/lgtm

2023-10-24 23:42 UTC, merged

2023-10-25 16:39 UTC, kaovilai commented
/cherry-pick oadp-1.2