doc: How to update OCP version jobs in CI
openshift/oadp-operator pull request #1237
Opened 2023-11-22 15:20 UTC by mateusoliveira43

Fixes https://github.com/openshift/oadp-operator/issues/1229

2023-11-22 15:21 UTC, mateusoliveira43 commented
This PR is blocked by https://github.com/openshift/release/pull/45918

2023-11-28 14:59 UTC, kaovilai requested changes

2023-11-28 14:59 UTC, kaovilai commented on docs/developer/PROW_CI.md
> +The configuration for OADP repo can be found in
perhaps add notes on plugins as well

2023-11-28 17:11 UTC, kaovilai commented on docs/developer/PROW_CI.md
> +The configuration for OADP repo can be found in
that's all

2023-11-29 18:20 UTC, merged

2023-11-29 18:20 UTC, weshayutin commented
@mateusoliveira43 THANK YOU for taking the time to put this together.  Folks this is a very nice start, merging. Patch as required :)