OADP-3586: Update to ubi9 builder and base images
openshift/oadp-operator pull request #1346
Opened 2024-02-27 17:33 UTC by weshayutin

See jira for details

2024-02-27 17:50 UTC, kaovilai submitted a review, later dismissed

2024-02-28 00:45 UTC, kaovilai commented
/retest-required

2024-02-28 00:55 UTC, kaovilai approved these changes

2024-02-28 01:00 UTC, kaovilai approved these changes
images ci passsed

/lgtm

2024-02-28 15:04 UTC, mateusoliveira43 commented on must-gather/Dockerfile
> +FROM registry.access.redhat.com/ubi8/go-toolset:1.20.10 AS gobuilder
ubi 9

2024-02-28 15:05 UTC, mateusoliveira43 requested changes
still ubi 8 refs

2024-02-29 16:48 UTC, weshayutin commented on must-gather/Dockerfile
> +FROM registry.access.redhat.com/ubi8/go-toolset:1.20.10 AS gobuilder
bah.. I suck, thank you!

2024-02-29 17:23 UTC, kaovilai approved these changes

2024-03-01 12:29 UTC, mateusoliveira43 commented
/retest

2024-03-01 16:17 UTC, kaovilai commented
/override ci/prow/4.12-e2e-test-azure 
/override ci/prow/4.13-e2e-test-azure

2024-03-01 16:20 UTC, merged