remove restartPolicy for OCP 4.16
openshift/oadp-operator pull request #1402
Opened 2024-05-30 16:38 UTC by weshayutin

* How to test Install Virt and deploy the fedora vm
Alternatively allow the e2e virt ci to hit it.

## Why the changes were made

4.16 deployments will fail if restartPolicy is defined

## How to test the changes made

 Install Virt and deploy the fedora vm
Alternatively allow the e2e virt ci to hit it.

2024-05-31 13:30 UTC, mateusoliveira43 requested changes
I think more changes are needed

If you run `grep -Iinr 'restartPolicy' .`, you can see that in `controllers/common.go` we enforce that restartPolicy is set (I believe that is passed to Velero and node-agent deployments)

EDIT
looking again, I think it is fine. The changes were made in `spec.template.spec.containers` and I was worried about doing changes in `spec.template.spec`

2024-06-04 13:06 UTC, mateusoliveira43 approved these changes
/lgtm
Tested in 4.16 cluster. This is basically a follow up of https://github.com/openshift/oadp-operator/commit/d06f5f71271c2915d94550a1b696b7d41ca7e2f8 , i.e., the problem is only in `spec.template.spec.containers` and not in `spec.template.spec`

2024-06-04 13:56 UTC, weshayutin commented
> /lgtm Tested in 4.16 cluster. This is basically a follow up of [d06f5f7](https://github.com/openshift/oadp-operator/commit/d06f5f71271c2915d94550a1b696b7d41ca7e2f8) , i.e., the problem is only in `spec.template.spec.containers` and not in `spec.template.spec`

ah.. nice catch. I have not yet been able to get virt up on OCP4.16, not working well on my cluster :/ We should hold the patch, perhaps it's not needed as you suggest.

2024-06-04 14:19 UTC, mateusoliveira43 commented
no need for virt to test this one (just OCP 4.15+), the change was just in the deployment object 

Did not understand last comment. I got confused reviewing the PR, because I though more things needed chnages, but what was changed is enough (and needed to work in 4.15+)

2024-06-04 20:31 UTC, mateusoliveira43 commented
/retest

2024-06-05 15:53 UTC, mateusoliveira43 commented
/override ci/prow/4.12-e2e-test-aws
restore succeeds but application not working flake

2024-06-05 16:01 UTC, merged