bump kubevirt to 0.6.2
openshift/oadp-operator pull request #1436
Opened 2024-06-20 18:10 UTC by kaovilai

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

## Why the changes were made

## How to test the changes made

2024-06-20 18:11 UTC, weshayutin commented on config/manager/manager.yaml
> +            value: quay.io/konveyor/akubevirt-velero-plugin:v0.6.2
typo

2024-06-20 18:11 UTC, weshayutin commented on pkg/common/common.go
> +	KubeVirtPluginImage  = "quay.io/konveyor/akubevirt-velero-plugin:v0.6.2"
typo

2024-06-20 18:11 UTC, mateusoliveira43 commented on bundle/manifests/oadp-operator.clusterserviceversion.yaml
> +                  value: quay.io/konveyor/akubevirt-velero-plugin:v0.6.2
typo?

2024-06-20 18:13 UTC, weshayutin approved these changes
/LGTM

2024-06-20 18:21 UTC, shubham-pampattiwar approved these changes

2024-06-20 18:37 UTC, rayfordj approved these changes
/lgtm

2024-06-20 20:28 UTC, rayfordj commented
/retest-required

2024-06-21 11:53 UTC, mateusoliveira43 commented
I saw some errors I never saw: api server may have been down. Should we investigate that?

2024-06-21 14:34 UTC, kaovilai commented
Error came from https://github.com/openshift/velero/pull/315

2024-06-21 14:38 UTC, weshayutin commented
> Error came from [openshift/velero#315](https://github.com/openshift/velero/pull/315)

uh oh..  Tiger please investigate this.

2024-06-21 14:47 UTC, kaovilai commented
Takes about 20 sec after creation to fail.
```
2024/06/20 21:04:31 Creating backup mysql-csi-e2e-90f0f6b7-2f48-11ef-a75a-0a580a812821 for case mysql-csi-e2e
2024/06/20 21:04:41 backup phase: InProgress
2024/06/20 21:04:52 backup phase: Failed
```

2024-06-21 15:04 UTC, kaovilai commented
/retest

2024-06-21 20:05 UTC, kaovilai commented
fix fyi: https://github.com/openshift/velero/pull/324/

2024-06-25 18:03 UTC, mateusoliveira43 requested changes
Also had the same problem here: If I add kubevirt plugin in DPA, velero container never succeeds with `Init:CrashLoopBackOff` with kubevirt plugin restarting 6 times in 10 minutes

2024-06-27 18:24 UTC, kaovilai commented
/hold for https://github.com/openshift/velero/pull/324

2024-06-27 20:11 UTC, kaovilai commented
/retest
/unhold

2024-06-28 05:17 UTC, kaovilai commented
/retest

2024-06-28 08:47 UTC, merged