Allow developer to specify e2e test name on cli
openshift/oadp-operator pull request #1526
Opened 2024-09-20 17:29 UTC by weshayutin

## Why the changes were made

BECAUSE, you shouldn't have to change src code to specify the dam test you want to execute.
GOLANG / Ginkgo pffft.

## How to test the changes made

make test-e2e TEST_ARGS="--ginkgo.focus='MySQL application DATAMOVER'"
should only run 1 test :)

2024-09-20 17:31 UTC, mrnold approved these changes

2024-09-20 18:18 UTC, shubham-pampattiwar submitted a review, later dismissed

2024-09-20 21:02 UTC, kaovilai commented on Makefile
> +	$(TEST_ARGS)
```suggestion
	$(GINKGO_ARGS)
```
?

2024-09-30 16:44 UTC, weshayutin commented on Makefile
> +	$(TEST_ARGS)
good suggestion, thank you @kaovilai

2024-09-30 16:48 UTC, kaovilai submitted a review, later dismissed
/lgtm

2024-09-30 16:51 UTC, mateusoliveira43 requested changes
TEST_ARGS -> GINKGO_ARGS

2024-09-30 16:57 UTC, weshayutin commented on docs/developer/testing/TESTING.md
> +You can also execute make test-e2e with a $TEST_ARGS variable set. Example:
ah dang, updated and also corrected the note about changing the code to specify which test to run.

2024-09-30 16:59 UTC, mateusoliveira43 approved these changes

2024-09-30 17:26 UTC, shubham-pampattiwar approved these changes

2024-09-30 19:45 UTC, weshayutin commented
/retest

2024-10-01 00:00 UTC, kaovilai commented
/lgtm

2024-10-01 03:09 UTC, merged