Exit loop if none of the secret file pattern matches
openshift/oadp-operator pull request #460
Opened 2021-11-17 19:24 UTC by deepakraj1997

2021-11-17 19:25 UTC, deepakraj1997 commented
/test-all

2021-11-18 02:30 UTC, shubham-pampattiwar requested changes
@deepakraj1997 Do you mind adding unit test for this scenario as well as other credential file parsing scenarios covering boundary cases ?

2021-11-18 16:49 UTC, deepakraj1997 commented
@shubham-pampattiwar  Thank you for reviewing, I did add a test case last time for testing profile but missing this corner case. I have added a new test case for this.

2021-11-19 17:09 UTC, dymurray approved these changes

2021-11-19 17:13 UTC, shubham-pampattiwar approved these changes

2021-11-19 17:13 UTC, merged