Add upgrade MTC-OADP integration upgrade steps
openshift/oadp-operator pull request #562
Opened 2022-02-01 08:59 UTC by shubham-pampattiwar

2022-02-01 15:21 UTC, rayfordj commented on docs/developer/MTC_OADP_Upgrade.md
> +- export TAF="your tag name"
```suggestion
- export TAG="your tag name"
```

2022-02-03 13:52 UTC, weshayutin commented
@shubham-pampattiwar is anyone automating the steps? Please ping me if there is interest in having it automated.
Thanks!

2022-02-03 16:45 UTC, rayfordj requested changes

2022-02-03 17:54 UTC, rayfordj commented on docs/developer/MTC_OADP_Upgrade.md
> +- Always stream the pod logs `catalog-oprator` pod from the `openshift-operator-lifecycle-manager` namespace when you edit
```suggestion
- Always stream the pod logs `catalog-operator` pod from the `openshift-operator-lifecycle-manager` namespace when you edit
```

2022-02-07 04:00 UTC, shubham-pampattiwar commented
> @shubham-pampattiwar is anyone automating the steps? Please ping me if there is interest in having it automated. Thanks!

@weshayutin Not that I am aware of. But yes seems like a good idea.

2022-02-07 13:13 UTC, dymurray approved these changes

2022-02-07 13:14 UTC, dymurray commented
@rayfordj Please re-review when you get a minute. Thanks!

2022-02-07 14:21 UTC, rayfordj approved these changes
/lgtm

2022-02-07 14:42 UTC, merged