replace the parks-app with todolist on mongo
openshift/oadp-operator pull request #649
Opened 2022-04-28 17:20 UTC by weshayutin

* created a version of todolist for mongo
* ensure the manifest builds and triggers just like
the parks-app did
* adv is that the same app api can be used to add
data to the db and check after restore. Related PR
https://github.com/openshift/oadp-operator/pull/624

Resolves: https://github.com/openshift/oadp-operator/issues/646

2022-04-28 17:21 UTC, weshayutin commented
/hold WIP

2022-04-28 18:12 UTC, deepakraj1997 commented
LGTM, Thank you for putting this up. Do we want to check CSI template as well as part of this ?

2022-04-28 18:25 UTC, weshayutin commented
> 

@deepakraj1997 We could use the CSI version but we should do add that row of test data in a new PR.

2022-04-28 18:32 UTC, hhpatel14 commented
/lgtm

2022-04-28 19:16 UTC, weshayutin commented
/unhold

2022-04-28 19:27 UTC, weshayutin commented
/retest

2022-04-29 14:22 UTC, kaovilai requested changes

2022-04-29 14:22 UTC, kaovilai commented on tests/e2e/backup_restore_suite_test.go
> +		Entry("Mongo application <4.8.0", BackupRestoreCase{
Since `Mongo application <4.8.0` is no longer using a different manifests, we can remove the other one.

2022-04-29 14:23 UTC, kaovilai commented on tests/e2e/backup_restore_suite_test.go
> +		Entry("Mongo application <4.8.0", BackupRestoreCase{
No longer different to `Mongo application >=4.8.0`.

2022-04-29 14:24 UTC, kaovilai commented on tests/e2e/backup_restore_suite_test.go
>  			MaxK8SVersion:        &K8sVersionOcp47,
```suggestion

```

2022-04-29 14:33 UTC, kaovilai commented
Have PR of requested changes here https://github.com/weshayutin/oadp-operator/pull/1

2022-05-03 12:33 UTC, weshayutin commented on tests/e2e/backup_restore_suite_test.go
> +		Entry("Mongo application >=4.8.0", BackupRestoreCase{
rock.. thanks

2022-05-03 12:34 UTC, weshayutin commented
@kaovilai THANK YOU! for you help reviewing this one :)

2022-05-03 14:33 UTC, weshayutin commented
/retest

2022-05-03 18:17 UTC, kaovilai approved these changes

2022-05-03 18:30 UTC, merged