Fix makefile awk err
openshift/oadp-operator pull request #705
Opened 2022-05-19 16:10 UTC by shubham-pampattiwar

Currently when you run `make test` locally you get the following error:
```
awk: cmd. line:1: {print tolower()}                                                                                                                                          
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower  
```
This PR fixes the error

2022-05-19 18:15 UTC, shubham-pampattiwar commented
/retest

2022-05-19 20:55 UTC, kaovilai commented on Makefile
> +ifeq ($0,"")
what does this do? when $0 is not empty don't set cluster_type?

2022-05-19 21:05 UTC, kaovilai commented on Makefile
>  CLUSTER_TYPE ?= $(shell $(OC_CLI) get infrastructures cluster -o jsonpath='{.status.platform}' | awk '{print tolower($0)}')
I think $0 here is run in a separate $(shell..) not the same shell as one that run `ifeq ($0,"")`

2022-05-27 01:26 UTC, kaovilai commented on Makefile
>  CLUSTER_TYPE ?= $(shell $(OC_CLI) get infrastructures cluster -o jsonpath='{.status.platform}' | awk '{print tolower($0)}')
```suggestion
CLUSTER_TYPE ?= ""
ifdef OC_CLI
	CLUSTER_TYPE ?= $(shell $(OC_CLI) get infrastructures cluster -o jsonpath='{.status.platform}')
endif
ifneq ($(CLUSTER_TYPE), "")
	CLUSTER_TYPE := $(shell echo $(CLUSTER_TYPE) | awk '{print tolower($0)}')
endif
```

2022-05-27 01:27 UTC, kaovilai requested changes
This should work.

2022-05-27 01:28 UTC, kaovilai commented
/cherrypick oadp-1.0

2022-06-03 17:30 UTC, shubham-pampattiwar commented
/retest

2022-06-03 19:07 UTC, kaovilai commented
/retest

2022-06-03 19:15 UTC, kaovilai commented
/meow

2022-06-03 20:01 UTC, kaovilai commented
```
INFO[2022-06-03T19:49:33Z] awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
```

2022-06-03 20:38 UTC, shubham-pampattiwar commented
/retest

2022-06-05 21:02 UTC, shubham-pampattiwar commented
/retest

2022-06-08 13:39 UTC, dymurray commented
/retest

2022-06-09 17:31 UTC, kaovilai requested changes

2022-06-09 17:31 UTC, kaovilai commented on Makefile
> +	CLUSTER_TYPE := $(shell echo $(CLUSTER_TYPE) | awk "{print tolower($0)}")
Trying @rayfordj AWKVAR
```suggestion
	CLUSTER_TYPE := $(shell echo $(CLUSTER_TYPE) | awk -v AWKVAR="${0}" '{print tolower(AWKVAR)}')
```

2022-09-08 19:30 UTC, weshayutin commented
wow.. worked for me locally .. tested w/o a cluster /me runs..
```
[whayutin@thinkdoe oadp-operator]$ make tests
awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
make: Nothing to be done for 'tests'.
[whayutin@thinkdoe oadp-operator]$ gh pr checkout 705
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 15 (delta 9), reused 9 (delta 9), pack-reused 4
Unpacking objects: 100% (15/15), 3.22 KiB | 549.00 KiB/s, done.
From https://github.com/openshift/oadp-operator
 * [new ref]         refs/pull/705/head -> fix-make-test
Switched to branch 'fix-make-test'
[whayutin@thinkdoe oadp-operator]$ make tests
make: Nothing to be done for 'tests'.

```

2022-09-08 19:30 UTC, weshayutin commented
/retest

2022-09-09 12:47 UTC, weshayutin commented
The error in CI is:
```
bash: /go/src/github.com/openshift/oadp-operator/bin/setup-envtest: No such file or directory
mkdir -p /tmp/test-settings
TARGET_CI_CRED_FILE="/var/run/secrets/ci.openshift.io/cluster-profile/.awscred" AZURE_RESOURCE_FILE="/var/run/secrets/ci.openshift.io/multi-stage/metadata.json" CI_JSON_CRED_FILE="/var/run/secrets/ci.openshift.io/cluster-profile/osServicePrincipal.json" \
OADP_JSON_CRED_FILE="/var/run/oadp-credentials/azure-credentials" OADP_CRED_FILE="/var/run/oadp-credentials/new-aws-credentials" OPENSHIFT_CI="true" \
PROVIDER="" BUCKET="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" BSL_REGION="us-east-1" SECRET="cloud-credentials" TMP_DIR=/tmp/test-settings \
VSL_REGION="us-east-2" BSL_AWS_PROFILE="default" /bin/bash "tests/e2e/scripts/_settings.sh"
/bin/bash: tests/e2e/scripts/_settings.sh: No such file or directory
make: *** [Makefile:429: test-e2e-setup] Error 127
```

2022-09-09 17:03 UTC, weshayutin commented
Line 40:
CLUSTER_TYPE ?= $(shell $(OC_CLI) get infrastructures cluster -o jsonpath='{.status.platform}' | awk '{print tolower($0)}')

Looks like this is not getting set correctly

2022-09-09 17:06 UTC, weshayutin commented on Makefile
> +		CLUSTER_TYPE := $(shell $(OC_CLI) get infrastructures cluster -o jsonpath='{.status.platform}')
ya.. we have a problem here, looking into it :)

2022-09-09 17:33 UTC, weshayutin commented on Makefile
> +ifneq ($(OC_CLI),)
we could try
```suggestion
CLUSTER_TYPE ?= $(shell $(OC_CLI) get infrastructures cluster -o jsonpath='{.status.platform}' | tr A-Z a-z)
$(info $$CLUSTER_TYPE is [${CLUSTER_TYPE}])
```

2022-09-12 12:12 UTC, weshayutin commented
@shubham-pampattiwar  tested fix here and it worked, https://github.com/openshift/oadp-operator/pull/820

2022-09-12 13:07 UTC, shubham-pampattiwar commented
Closing this PR in favor of https://github.com/openshift/oadp-operator/pull/820

2022-09-12 13:07 UTC, closed without merging