OADP-535 allow for nullable resource allocations
openshift/oadp-operator pull request #711
Opened 2022-05-25 21:38 UTC by dymurray

This change allows for null resource allocations fields.

**NOTE** this includes a manual update to the DPA CRD to allow for `null` requests and allocations fields. This means that `make manifests` will no longer give us exactly what we need and will require folks to constantly add it back in. We need to figure out a better path forward for this.
[OADP-535](https://issues.redhat.com//browse/OADP-535)

2022-05-26 03:51 UTC, kaovilai commented
/cherrypick oadp-1.0

2022-05-26 04:40 UTC, shubham-pampattiwar commented on bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
>                                    x-kubernetes-int-or-string: true
Don't  we need `nullable: true` on line number 209 as well as on line number 353.

2022-05-26 04:41 UTC, shubham-pampattiwar commented on config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
>                                  additionalProperties:
Don't  we need `nullable: true` specifically for limits as well as requests ?

2022-05-26 13:13 UTC, dymurray commented
/cherrypick oadp-1.0

2022-05-27 12:49 UTC, pranavgaikwad requested changes

2022-05-27 12:49 UTC, pranavgaikwad commented on bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
>                                  additionalProperties:
needs `nullable` for the additionalProperties.

2022-05-27 14:05 UTC, pranavgaikwad approved these changes
ACK, thank you for the fix!

2022-05-27 14:19 UTC, jmontleon commented
/lgtm

2022-05-27 14:25 UTC, merged

2022-05-27 14:26 UTC, dymurray commented
/cherrypick oadp-1.0