Doc: correct fields, link updates.
openshift/oadp-operator pull request #783
Opened 2022-08-08 14:41 UTC by kaovilai

2022-08-08 14:42 UTC, kaovilai commented on docs/API_ref.md
> +| bucket   | [*CloudStorageLocation](https://pkg.go.dev/github.com/openshift/oadp-operator@master/api/v1alpha1#CloudStorageLocation) | Location to store volume snapshots. For further details, see  [h
Notable change 1

2022-08-08 14:45 UTC, kaovilai commented on docs/API_ref.md
> +| bucket   | [*CloudStorageLocation](https://pkg.go.dev/github.com/openshift/oadp-operator@master/api/v1alpha1#CloudStorageLocation) | Location to store volume snapshots. For further details, see  [h
gotta fix description for bucket

2022-08-08 14:57 UTC, kaovilai commented on docs/API_ref.md
> +| bucket   | [*CloudStorageLocation](https://pkg.go.dev/github.com/openshift/oadp-operator@master/api/v1alpha1#CloudStorageLocation) | [Tech Preview] Automate creation of bucket at some cloud storage
Notable change 1

2022-08-08 15:08 UTC, kaovilai commented on docs/API_ref.md
> +| bucket   | [*CloudStorageLocation](https://pkg.go.dev/github.com/openshift/oadp-operator@master/api/v1alpha1#CloudStorageLocation) | [Tech Preview] Automates creation of bucket at some cloud storag
Notable change 1

2022-08-10 19:39 UTC, shubham-pampattiwar approved these changes

2022-08-10 19:44 UTC, eemcmullan requested changes

2022-08-10 19:44 UTC, eemcmullan commented on docs/API_ref.md
> +| velero   | [*velero.BackupStorageLocationSpec](https://velero.io/docs/v1.9/api-types/backupstoragelocation/) | Location to store volume snapshots. For further details, see  [here](config/bsl_and_vs
Location to store backup objects?

2022-08-10 19:47 UTC, dymurray approved these changes

2022-08-10 20:33 UTC, kaovilai commented on docs/API_ref.md
> +| velero   | [*velero.BackupStorageLocationSpec](https://velero.io/docs/v1.9/api-types/backupstoragelocation/) | Location to store volume snapshots. For further details, see  [here](config/bsl_and_vs
thx

2022-08-10 20:48 UTC, eemcmullan approved these changes

2022-08-10 21:03 UTC, merged