detect sha256sum is working else use shasum
openshift/oadp-operator pull request #793
Opened 2022-08-17 16:25 UTC by kaovilai

2022-08-17 16:28 UTC, sseago approved these changes

2022-08-17 16:44 UTC, sseago requested changes

2022-08-17 16:44 UTC, sseago commented on docs/scripts/dc-restic-post-restore.sh
> +    sha=$(echo -n $1|checksum_cmd)
This needs to be 
```
    sha=$(echo -n $1|$checksum_cmd)
```

2022-08-17 16:46 UTC, sseago approved these changes

2022-08-17 17:07 UTC, shubham-pampattiwar approved these changes

2022-08-17 17:16 UTC, merged

2022-08-24 17:39 UTC, kaovilai commented
/cherrypick oadp-1.1
Not blocker but nice to have.